
sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t oleggorj/ubuntu16.04-ansible ubuntu/16.04/

script:
    - bash ./tests/ubuntu_1604.sh

after_script:
    - docker ps -a
    - docker logs my_ubuntu16.04-ansible
